$(document).ready(function(){
  	$(".main-carousel").owlCarousel({
	  	loop:true,
	    margin:10,
	    nav:true,
	    autoplay:true,
	    autoplayTimeout:2000,
	    autoplayHoverPause:true,
	    responsive:{
	        320:{
	            items:1,
	    		nav:false
	        },
	        576:{
	            items:1,
	    		nav:false
	        },
	        1000:{
	            items:1,
	    		nav:true
	        }
	    }
  	});

  	$(".news-carousel").owlCarousel({
	  	loop:true,
	    margin:3,
	    nav:true,
	    autoplay:true,
	    autoplayTimeout:2000,
	    autoplayHoverPause:true,
	    responsive:{
	        320:{
	            items:1,
	            nav:false
	        },
	        426:{
	            items:2,
	            nav:false
	        },
	        769:{
	            items:4,
	            nav:true
	        }
	    }
  	});

  	$(".new-post__logos").owlCarousel({
	  	loop:true,
	    margin:16,
	    autoplay:true,
	    autoplayTimeout:2000,
	    autoplayHoverPause:true,
	    responsive:{
	        320:{
	            items:2
	        },
	        577:{
	            items:3
	        },
	        769:{
	            items:4
	        },
	        993: {
	        	items:6
	        }
	    }
  	});

  	$(".blog-pages").owlCarousel({
	  	loop:false,
	    margin:16,
	    merge:true,
	    responsive:{
	        320:{
	            mergeFit:true,
	            items:2
	        },
	        577:{
	            mergeFit:true
	        },
	        769:{
	            mergeFit:true,
	        	items:4
	        },
	        993: {
	        	mergeFit:true,
	        	items:4
	        }
	    }
  	})
});